name: '@dictav/protoc'
description: 'protoc action'
inputs:
  protoc_flags:
    description: 'flags and args of protoc'
    require: false
  make:
    description: 'Makefile Task'
    require: false
  bash:
    description: 'Bash file'
    require: false
  workdir:
    description: 'Working directory relative to the root directory'
    require: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.protoc_flags }}
