name: '@dictav/protoc'
description: 'protoc action'
inputs:
  protoc_flags:
    description: 'flags and args of protoc'
    default: '--help'
    require: false
  make:
    description: 'Makefile Task'
    require: false
  bash:
    description: 'Bash file'
    require: false
  working-directory:
    description: 'Working directory relative to the root directory'
    require: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.protoc_flags }}
  env:
    WORKING_DIRECTORY: ${{ inputs.working-directory }}
    MAKE_TASK: ${{ inputs.make }}
    BASH_FILE: ${{ inputs.bash }}
